fix cargo-mutagen usage as cargo subcommand
cargo passes all args to the subcommand program, which means our binary
will receive "mutagen" as first argument when invoked like this:

     $ cargo mutagen

This produced an error, because structopt doesn't expect a "mutagen"
argument at all:

     error: Found argument 'mutagen' which wasn't expected, or isn't
     valid in this context

     USAGE:
         cargo-mutagen [FLAGS] [OPTIONS]

         For more information try --help